<div class="nota_element" style="background-color:#CCC;">1</div>
<div class="nota_element" style="background-color:#CCC;">2</div>
<div class="nota_element" style="background-color:#CCC;">3</div>
<div class="nota_element" style="background-color:#CCC;">4</div>
<div class="nota_element" style="background-color:#CCC;">5</div>
<div class="nota_element" style="background-color:#CCC;">6</div>
<div class="nota_element" style="background-color:#CCC;">7</div>
<div class="nota_element" style="background-color:#CCC;">8</div>
<div class="nota_element" style="background-color:#CCC;">9</div>
<div class="nota_element" style="background-color:#CCC;">10</div>